services:
  elasticsearch:
    build:
      context: .
      dockerfile_inline: |
        ARG STACK_VERSION
        FROM docker.elastic.co/elasticsearch/elasticsearch:${STACK_VERSION}
        RUN bin/elasticsearch-plugin install analysis-icu
      args:
        STACK_VERSION: ${STACK_VERSION}
    labels:
      co.elastic.logs/module: elasticsearch
    restart: unless-stopped
    environment:
      node.name: es
      cluster.name: ${CLUSTER_NAME}
      ELASTIC_PASSWORD: ${ELASTIC_PASSWORD}
      bootstrap.memory_lock: true
      xpack.security.enabled: true
      xpack.security.http.ssl.enabled: true
      xpack.security.http.ssl.key: certs/elastic-cert-key.pem
      xpack.security.http.ssl.certificate: certs/elastic-cert.pem
      xpack.security.http.ssl.certificate_authorities: certs/root-ca.pem
      xpack.security.transport.ssl.enabled: true
      xpack.security.transport.ssl.key: certs/elastic-cert-key.pem
      xpack.security.transport.ssl.certificate: certs/elastic-cert.pem
      xpack.security.transport.ssl.certificate_authorities: certs/root-ca.pem
      xpack.security.transport.ssl.verification_mode: certificate
      xpack.license.self_generated.type: ${LICENSE}
      ingest.geoip.downloader.enabled: false
      path.repo: /mount/backups
    secrets:
      - source: root-ca
        target: /usr/share/elasticsearch/config/certs/root-ca.pem
      - source: elastic-cert
        target: /usr/share/elasticsearch/config/certs/elastic-cert.pem
      - source: elastic-cert-key
        target: /usr/share/elasticsearch/config/certs/elastic-cert-key.pem
    mem_limit: ${ES_MEM_LIMIT}
    ulimits:
      memlock:
        soft: -1
        hard: -1
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl -s --cacert /usr/share/elasticsearch/config/certs/root-ca.pem https://localhost:9200 | grep -q 'missing authentication credentials'"
        ]
      interval: 10s
      timeout: 10s
      retries: 120
