services:
  kibana:
    image: docker.elastic.co/kibana/kibana:${STACK_VERSION}
    labels:
      co.elastic.logs/module: kibana
    ports:
      - ${KIBANA_PORT}:5601
    restart: unless-stopped
    environment:
      SERVERNAME: kibana
      SERVER_SSL_ENABLED: true
      SERVER_SSL_KEY: config/certs/elastic-cert-key.pem
      SERVER_SSL_CERTIFICATE: config/certs/elastic-cert.pem
      SERVER_SSL_CERTIFICATEAUTHORITIES: config/certs/root-ca.pem
      SERVER_PUBLICBASEURL: https://kibana.local
      ELASTICSEARCH_USERNAME: kibana_system
      ELASTICSEARCH_PASSWORD: ${KIBANA_PASSWORD}
      ELASTICSEARCH_SSL_CERTIFICATEAUTHORITIES: config/certs/root-ca.pem
      XPACK_SECURITY_ENCRYPTIONKEY: ${ENCRYPTION_KEY}
      XPACK_ENCRYPTEDSAVEDOBJECTS_ENCRYPTIONKEY: ${ENCRYPTION_KEY}
      XPACK_REPORTING_ENCRYPTIONKEY: ${ENCRYPTION_KEY}
    secrets:
      - source: root-ca
        target: /usr/share/kibana/config/certs/root-ca.pem
      - source: elastic-cert
        target: /usr/share/kibana/config/certs/elastic-cert.pem
      - source: elastic-cert-key
        target: /usr/share/kibana/config/certs/elastic-cert-key.pem
    mem_limit: ${KB_MEM_LIMIT}
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl -s -I http://localhost:5601 | grep -q 'HTTP/1.1 302 Found'"
        ]
      interval: 10s
      timeout: 10s
      retries: 120