services:
  setup:
    image: docker.elastic.co/elasticsearch/elasticsearch:${STACK_VERSION}
    restart: no
    user: "0"
    secrets:
      - source: root-ca
        target: root-ca.pem
    command: >
      bash -c '
        if [ x${ELASTIC_PASSWORD} == x ]; then
          echo "Set the ELASTIC_PASSWORD environment variable in the .env file";
          exit 1;
        elif [ x${KIBANA_PASSWORD} == x ]; then
          echo "Set the KIBANA_PASSWORD environment variable in the .env file";
          exit 1;
        fi;

        echo "Setting kibana_system password";
        curl -s -X POST --cacert /run/secrets/root-ca.pem -u "elastic:${ELASTIC_PASSWORD}" -H "Content-Type: application/json" -d "{ \"password\": \"${KIBANA_PASSWORD}\" }" https://es:9200/_security/user/kibana_system/_password;

        echo "Adding snapshot repository";
        curl -s -X PUT --cacert /run/secrets/root-ca.pem -u "elastic:${ELASTIC_PASSWORD}" -H "Content-Type: application/json" -d "{ \"type\": \"fs\", \"settings\": { \"location\": \"elasticsearch\" } }" https://es:9200/_snapshot/local;

        echo "All done!";
      '