services:
  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak
    restart: unless-stopped
    ports:
      - 8080:8080
    command: start-dev --proxy-headers xforwarded
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: ${KC_BOOTSTRAP_ADMIN_USERNAME}
      KC_BOOTSTRAP_ADMIN_PASSWORD: ${KC_BOOTSTRAP_ADMIN_PASSWORD}
      KC_DB: postgres
      KC_DB_URL_HOST: host.docker.internal
      KC_DB_USERNAME: ${PG_USER}
      KC_DB_PASSWORD: ${PG_PASSWORD}
