services:
  nginx:
      container_name: nginx
      image: nginx:1
      restart: always
      volumes:
        - ./conf.d:/etc/nginx/conf.d
        - ./certs:/etc/nginx/certs
      ports:
        - 80:80
        - 443:443